apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: marceleza
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: git-credentials
  timeout: 20s
  url: https://github.com/mmmarceleza/mykind.git

---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: flux-system
data:
  username: bWFyY2Vsby5tZWxvQHByb3Rvbm1haWwuY29t
  password: Z2hwX293RlhwTjlkMXFQbkFBVjFvNmlDZFpCZmxkeGZDcTNZb3RYTA==

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/staging/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: marceleza
    namespace: flux-system

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: getup
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.getup.io/getupcloud

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: regcred
#   namespace: flux-system
# data:
#   .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXMXRZWEpqWld4bGVtRTZOemMyWWpCa1pURXRNekUzWVMwMFkyRTNMV0ZtTmpjdFlUVTNaRGxsWldGa05USTUiCgkJfQoJfQp9
# type: kubernetes.io/dockerconfigjson
